image bg neutral = "Backgrounds/neutral.jpg"
image bg slide1 = "Backgrounds/slide-1.png"
image bg slide2 = "Backgrounds/slide-2.png"
image bg slide3 = "Backgrounds/slide-5.png"
image bg slide4 = "Backgrounds/slide-7.png"
image bg slide5 = "Backgrounds/slide-10.png"
